project:
  type: book
  output-dir: docs

bibliography: library/references.bib
date: last-modified
date-format: "MMM YYYY"

book:
  title: "Microbiome AnalysisSystem"
  subtitle: "From Microbial Communities to Defensible Biological Insights"
  author: "Teresia Mrema Buza | Complex Data Insights"
  chapters:
    - index.qmd
    - 00-preface.qmd
    - 01-system-overview.qmd
    - 02-study-design-and-metadata.qmd
    - 03-sample-collection-and-sequencing.qmd
    - 04-data-acquisition.qmd
    - 05-quality-control.qmd
    - 06-feature-generation.qmd
    - 07-taxonomic-profiling.qmd
    - 08-diversity-analysis.qmd
    - 09-functional-profiling.qmd
    - 10-differential-analysis.qmd
    - 11-biological-interpretation.qmd
    - 12-reproducible-reporting.qmd
    - 13-workforce-readiness.qmd

  appendices:
    - 999-appendix.qmd
    - 999-references.qmd


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    number-depth: 2
    smooth-scroll: true
    anchor-sections: true
    link-external-icon: true
    css: assets/css/cdi.css
    code-fold: true
    mermaid:
      theme: forest

execute:
  echo: true
  warning: false
  message: false
  freeze: auto
  working-dir: .

